FROM jenkins/jenkins:jdk21

USER root

WORKDIR /var/jenkins_home 

RUN apt-get update -y && \
    apt-get install -y wget php php-mbstring php-xml php-dom php-xmlwriter php-curl

COPY bin/composer .
RUN mv composer /usr/local/bin/composer

USER jenkins