FROM php:8.4-fpm

WORKDIR /var/www/html

RUN apt-get update -y && \
    apt-get install -y wget git unzip

COPY composer.json ./
COPY scripts/install_composer.sh ./

RUN chmod +x install_composer.sh && \
    ./install_composer.sh && \
    php composer.phar update

COPY ./public .
COPY ./src .