FROM jenkins/jenkins:jdk21

USER root

WORKDIR /var/jenkins_home 

RUN apt-get update -y && \
    apt-get install -y wget php php-mbstring php-xml php-dom php-xmlwriter php-curl

RUN wget -O phpunit.phar https://phar.phpunit.de/phpunit-10.phar && \
    chmod +x phpunit.phar && \
    mv phpunit.phar /usr/local/bin/phpunit

USER jenkins