services:
    ws-server:
        build:
            context: .
            dockerfile: ./local/Dockerfile.ws
        volumes:
            - .:/app
        networks:
            - seminary_network
    
    php-web:
        build:
            context: .
            dockerfile: local/Dockerfile.web
        volumes:
        - ./public:/var/www/html
        expose:
            - "9000"
        networks:
            - seminary_network

    nginx:
        image: nginx
        ports:
            - "8080:8080"
        volumes:
            - ./local/nginx.conf:/etc/nginx/nginx.conf
            - ./public:/var/www/html
        depends_on:
            - php-web
        networks:
            - seminary_network

networks:
    seminary_network: